### ISSUE TITLE
Confused about this change

### ISSUE THREAD

**Issue by LehmannDev** [ReactjsProgram/ES6-for-React-Curriculum#4]
https://github.com/tylermcginnis/Modern-JavaScript-Curriculum/blob/f087365747294a2dc714983ff1df19897e3c1277/app/containers/ForecastContainer.js#L41

Is it written this way to clarify that this handle Click will need a weather object when it gets connected to the Forecast Component?

**Comment by tylermcginnis** [comment]
Nope. Just looks like a mistake. `handleClick={this.handleClick}`.
